services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: taskapp-jenkins
    user: root
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
