services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: taskapp-postgres
    environment:
      - 'POSTGRES_DB=taskapp'
      - 'POSTGRES_PASSWORD=taskapp'
      - 'POSTGRES_USER=taskapp'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data:
