spring.application.name=taskApp
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskapp}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:taskapp}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:taskapp}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.output.ansi.enabled=ALWAYS
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000


# Frontend aktivasyon base URL'i (linkte kullanılacak)
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}
